name = "image-background-remover"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "image-bg-remover-db"
database_id = "4e5fbbc1-598b-4bfc-a7cc-0a3407678a95"
